version: "3.8"

volumes:
  caddy_data:
  caddy_config:
  prometheus:
  grafana:

configs:
  caddyfile:
    file: ./etc/Caddyfile
  prometheus:
    file: ./etc/prometheus.yml

services:
  caddy:
    image: vantt/caddy:2.3.0
    restart: unless-stopped
    ports:
      - "80:80"
      - 2019:2019
    configs:
      - source: Caddyfile
        target: /etc/caddy/Caddyfile
    volumes:
      - ./etc/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config


  prometheus:
      image: prom/prometheus:latest
      ports:
        - 9090:9090
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
      configs:
        - source: prometheus
          target: /etc/prometheus/prometheus.yml
      volumes:
        - prometheus:/prometheus
        - ./etc/prometheus.yml:/etc/prometheus/prometheus.yml
      deploy:
        mode: replicated
        replicas: 1
        placement:
          constraints:
            - node.role == manager
        resources:
          limits:
            memory: 2048M
          reservations:
            memory: 128M

  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      #- GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL:-localhost}
      #- GF_SMTP_ENABLED=${GF_SMTP_ENABLED:-false}
      #- GF_SMTP_FROM_ADDRESS=${GF_SMTP_FROM_ADDRESS:-grafana@test.com}
      #- GF_SMTP_FROM_NAME=${GF_SMTP_FROM_NAME:-Grafana}
      #- GF_SMTP_HOST=${GF_SMTP_HOST:-smtp:25}
      #- GF_SMTP_USER=${GF_SMTP_USER}
      #- GF_SMTP_PASSWORD=${GF_SMTP_PASSWORD}
    volumes:
      - grafana:/var/lib/grafana